"""add ingestion_tasks table and document version

Revision ID: b70458679ad5
Revises: 257cf43679ca
Create Date: 2026-08-26 17:10:58.204150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70458679ad5'
down_revision: Union[str, Sequence[str], None] = '257cf43679ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 系统占位用户：用于接管「引入用户体系之前已存在的孤儿会话」，
# 以及被硬删除用户触发 ON DELETE SET NULL 产生的会话。
# 固定 UUID + status=disabled，登录会被 auth_service 拦在 verify_password 之前；
# 应用层可按 username 前缀 '__' 排除。
PLACEHOLDER_USER_ID = "00000000-0000-0000-0000-000000000001"
PLACEHOLDER_USERNAME = "__system_placeholder__"


def upgrade() -> None:
    """Upgrade schema."""
    # --- 数据修复：必须先把 conversations.user_id 的 NULL 行处理掉，
    #     否则下一步 ALTER ... SET NOT NULL 会失败。
    bind = op.get_bind()
    # 1) 创建占位用户（idempotent，重复跑迁移安全）
    bind.execute(
        sa.text(
            "INSERT INTO users (id, username, password_hash, display_name, status) "
            "VALUES (:id, :username, :password_hash, :display_name, :status) "
            "ON CONFLICT (username) DO NOTHING"
        ),
        {
            "id": PLACEHOLDER_USER_ID,
            "username": PLACEHOLDER_USERNAME,
            # 非 bcrypt 格式串；即便被 verify_password 撞上也会返回 False
            "password_hash": "!disabled-placeholder!",
            "display_name": "系统占位",
            "status": "disabled",
        },
    )
    # 2) 把 user_id IS NULL 的历史会话挂到占位用户
    bind.execute(
        sa.text("UPDATE conversations SET user_id = :uid WHERE user_id IS NULL"),
        {"uid": PLACEHOLDER_USER_ID},
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('task_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('progress_done', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_tasks_document_id'), 'ingestion_tasks', ['document_id'], unique=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.add_column('documents', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # op.drop_index(op.f('ix_documents_permission_tags'), table_name='documents', postgresql_using='gin')
    op.create_index(
        "ix_ingestion_tasks_document_created",
        "ingestion_tasks",
        ["document_id", sa.text("created_at DESC")],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_documents_permission_tags'), 'documents', ['permission_tags'], unique=False, postgresql_using='gin')
    op.drop_column('documents', 'version')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_ingestion_tasks_document_id'), table_name='ingestion_tasks')
    op.drop_table('ingestion_tasks')
    # ### end Alembic commands ###
